---
- name: Add Apache options to make.conf
  lineinfile:
    path: /etc/portage/make.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
    backup: "{{ apache_backup_configurations | default('yes') }}"
  with_items:
    - regexp: '\w*.*APACHE2_MPMS='
      line: "APACHE2_MPMS=\"{{ apache_gentoo_mpms | default(_apache_gentoo_mpms) | join(' ') }}\""
    - regexp: '\w*.*APACHE2_MODULES='
      line: "APACHE2_MODULES=\"{{ apache_gentoo_modules | default(_apache_gentoo_modules) | join(' ') }}\""

- name: Update /etc/conf.d/apache2
  lineinfile:
    path: /etc/conf.d/apache2
    regexp: '\w*.*APACHE2_OPTS='
    line: "APACHE2_OPTS=\"{{ apache_gentoo_opts }}\""
    backup: yes

- name: Check type of /etc/portage/package.use
  stat:
    path: /etc/portage/package.use
  register: package_use_stat

- name: Update Apache use flags in /etc/portage/package.use
  lineinfile:
    path: /etc/portage/package.use
    regexp: '^www\-servers\/apache'
    line: "www-servers/apache {{ apache_gentoo_flags | default(_apache_gentoo_flags) | join(' ') }}"
    state: present
    backup: "{{ apache_backup_configurations | default('yes') }}"
  when: package_use_stat.stat.exists and package_use_stat.stat.isreg

- name: Update Apache use flags in /etc/portage/package.use/apache
  lineinfile:
    path: /etc/portage/package.use/apache
    regexp: '^www\-servers\/apache'
    line: "www-servers/apache {{ apache_gentoo_flags | default(_apache_gentoo_flags) | join(' ') }}"
    state: present
    create: yes
    backup: "{{ apache_backup_configurations | default('yes') }}"
  when: package_use_stat.stat.exists and package_use_stat.stat.isdir

- name: Install Apache
  portage:
    newuse: yes
    update: yes
    sync: yes
    package: "www-servers/apache"
    quiet: yes
    state: present

- name: "Update /etc/apache2/httpd.conf"
  lineinfile:
    path: "/etc/apache2/httpd.conf"
    regexp: '\w*.*ServerRoot'
    line: "ServerRoot \"{{ apache_server_root[ansible_distribution] }}\""
    state: present
    backup: yes

- name: "Update /etc/apache2/vhosts.d/00_default_vhost.conf"
  lineinfile:
    path: "/etc/apache2/vhosts.d/00_default_vhost.conf"
    regexp: '\w*.*Listen 80'
    line: "Listen {{ apache_listen | default('80') }}"
    state: present
    backup: yes
