---
- name: Import Apache Install Tasks
  include_tasks: "{{ ansible_os_family }}/main.yml"

- name: Create Hosting File Structure
  file:
    path: "{{ apache_vhost_base_directory }}/{{ item[0]['server_name'] }}/{{ item[1] }}"
    group: "{{ item[0]['group'] }}"
    state: directory
    owner: "{{ item[0]['owner'] }}"
  with_nested:
    - "{{ apache_vhosts }}"
    - "{{ apache_vhost_directories }}"

- name: "Create vhosts configuration directory"
  file:
    path: "{{ item }}"
    owner: root
    group: root
    state: directory
  with_items:
    - "{{ _apache_server_root[ansible_distribution] }}/conf.d"
    - "{{ _apache_server_root[ansible_distribution] }}/conf.d/vhosts"

- name: "Create vhost files"
  template:
    dest: "{{ _apache_server_root[ansible_distribution] }}/conf.d/vhosts/{{ item['server_name'] | replace('.', '_') }}.conf"
    src: "vhost.conf.j2"
    owner: root
    group: root
  with_items:
    - "{{ apache_vhosts }}"

- name: "Craete ssl-vhost files"
  template:
    dest: "{{ _apache_server_root[ansible_distribution] }}/conf.d/vhosts/{{item['server_name'] | replace('.', '_') }}-ssl.conf"
    src: "vhost-ssl.conf.j2"
    owner: root
    group: root
  with_items:
    - "{{ apache_ssl_vhosts }}"

- name: Import SELinux Tasks
  include_tasks: selinux.yml
  when: ansible_selinux['status'] is defined and ansible_selinux['status'] == enabled
