---
- name: Import Apache Install Tasks
  include_tasks: "{{ ansible_os_family }}/main.yml"

- name: Create Hosting File Structure
  file:
    path: "{{ apache_vhost_base_directory }}/{{ item[0]['server_name'] }}/{{ item[1] }}"
    group: "{{ item[0]['group'] }}"
    state: directory
    owner: "{{ item[0]['owner'] }}"
  with_nested:
    - "{{ apache_vhosts }}"
    - "{{ apache_vhost_directories }}"

- name: Import SELinux Tasks
  include_tasks: selinux.yml
  when:
