---
- name: "Import {{ ansible_distribution }} {{ ansible_distribution_major_version }}"
  include_tasks: "{{ansible_distribution }}/main.yml"


- name: Install Apache
  yum:
    name: "{{ item }}"
  with_items: "{{ _apache_rh_packages }}"
  notify: "Start httpd"
